"""
This script reads the JSON report generated by Google OSV-Scanner.

It loads the JSON data and returns it to the main application for further processing.

Parameters:
    file_path (str): Path to the JSON results file.

Returns the parsed JSON data if successful.
"""

import json
from cvss import CVSS3

def load_results(file_path):

    try:
        with open(file_path, "r") as file:
            data = json.load(file)

        return data

    except Exception as error:
        print(f"An unexpected error occurred: {error}")
        return None

"""
CVSS Extraction Function

Extracts CVSS score from the OSV severity vector.

Parameters:
    vulnerability (dict): Vulnerability entry from the OSV JSON

Returns:
    float: Numerical CVSS score, otherwise None.
"""

def extract_cvss_score(vulnerability):

    if "severity" not in vulnerability:
        return None

    for severity in vulnerability["severity"]:

        if severity["type"] == "CVSS_V3":

            vector = severity["score"]

            try:
                cvss = CVSS3(vector)
                return cvss.scores()[0]

            except Exception:
                return None

    return None


"""
Vulnerability Extraction Function
Extracts basic vulnerability information from the JSON report.

Parameters:
    data (dict): Parsed JSON data

Returns:
    list: A list containing vulnerability information.
"""

def extract_vulnerabilities(data):

    vulnerabilities = []

    for result in data["results"]:

        for package in result["packages"]:

            package_name = package["package"]["name"]
            package_version = package["package"]["version"]

            for vulnerability in package["vulnerabilities"]:
                # Get all aliases (if they exist)
                aliases = vulnerability.get("aliases", [])

                # Look for a CVE identifier
                cve = None

                for alias in aliases:
                    if alias.startswith("CVE-"):
                        cve=alias
                        break
                
                cvss = extract_cvss_score(vulnerability)

                vulnerabilities.append({
                    "package": package_name,
                    "version": package_version,
                    "osv_id": vulnerability["id"],
                    "cve": cve,
                    "cvss": cvss
                })

                # Fill in missing CVSS scores using matching CVE records
                for vulnerability in vulnerabilities:
                    
                    if vulnerability["cvss"] is None:

                        for other in vulnerabilities:

                            if vulnerability["cve"] == other["cve"]:

                                if other["cvss"] is not None:

                                    vulnerability["cvss"] = other["cvss"]
                                    
                                    break

    return vulnerabilities